name: Test
on: [push, pull_request]
jobs:

  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Oracle container
        uses: gvenzl/setup-oracle-free@v1
        with:
          container-runtime: docker
          app-user: app_user
          app-user-password: app_user_password

      - name: Setup SQLcl
        uses: gvenzl/setup-oracle-sqlcl@v1

      - name: Connect to DB
        run: |
          echo "select * from v\$version;" | ${SQLCL_HOME}/bin/sql app_user/app_user_password@localhost:1521/FREEPDB1
